version: "3.1"

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.slurm.controller
    image: slurm-controller
    container_name: controller
    privileged: true
    # restart: always
    hostname: controller
    command: tail -f /dev/null
    networks:
      - slurm
    volumes:
      - secrets:/secrets

  compute1:
    build:
      context: .
      dockerfile: Dockerfile.slurm.compute
    image: slurm-compute
    depends_on:
      - controller
    container_name: compute1
    privileged: true
    # restart: always
    hostname: compute1
    command: tail -f /dev/null
    networks:
      - slurm
    volumes:
      - secrets:/secrets

  compute2:
    build:
      context: .
      dockerfile: Dockerfile.slurm.compute
    image: slurm-compute
    depends_on:
      - controller
    container_name: compute2
    privileged: true
    # restart: always
    hostname: compute2
    command: tail -f /dev/null
    networks:
      - slurm
    volumes:
      - secrets:/secrets

networks:
  slurm:

volumes:
  secrets:
