FIOL_ACCELERATOR:
  SRO_SEQUENCE_LENGTH:
    type: int
    description:
    default: 100
    env_var: True

  SRO_DSC_BINSIZE:
    type: int
    description:
    default: 1048576
    env_var: True

  SRO_CLUSTER_THRESHOLD:
    type: int
    description:
    default: 2
    env_var: True

  SRO_PREFETCH_SIZE:
    type: int
    description:
    default: 20971520
    env_var: True

  IOLIB_DISABLE_SIGNALS_BLOCKING:
    type: int
    description: allows to disable signal blocking
    default: 0
    env_var: True

  SRO_DISABLE_WRITE_PREFETCH:
    type: int
    description: allow to disable SRO write prefetching
    default: 0
    env_var: True

  SRO_ALLOW_SEQ_PREFETCH:
    type: int
    description: allow SRO to prefetch when sequential pattern are detected
    default: 0
    env_var: True

  SRO_PREFETCH_TECHNIQUE:
    type: int
    description: allow to do readahead operations (ie asynchronous read) instead of synchronous read
    default: 0
    env_var: True

  SLURM_CONF:
    type: str
    ask_user: True
    env_var: True
    default: /etc/slurm/slurm.conf
    description: Path to the Slurm configuration of the cluster

SBB_SLURM_ACCELERATOR:
  SLURM_CONF:
    type: str
    ask_user: True
    env_var: True
    default: /etc/slurm/slurm.conf
    description: Path to the Slurm configuration of the cluster

  FLAVOR:
    type: str
    ask_user: True
    description: Enter one existing flavor for the SBB accelerator that will be used as default. The flavors can be found at /etc/flash-accelerators/datanodes.conf.

  TARGETS:
    type: str
    default: /fs1/

  WORKERS:
    type: int
    default: 10
    optional: True

  MAX-RDMA-SIZE:
    type: int
    default: 1052672
    optional: True

  MAX-IO-SIZE:
    type: int
    default: 1073741824
    optional: True

  FLASH-CACHE-THRESHOLD:
    type: int
    default: 90
    optional: True

  FLASH-DESTAGERS:
    type: int
    default: 10
    optional: True

  MAX-FLASH-DESTAGE-SIZE:
    type: int
    default: 1048576
    optional: True

  MAX-FLASH-DESTAGE-OPS:
    type: int
    default: 100
    optional: True

  MAX-FLASH-DESTAGE-TIME:
    type: int
    optional: True

  RAM-CACHE-THRESHOLD:
    type: int
    default: 90
    optional: True

  RAM-DESTAGERS:
    type: int
    default: 10
    optional: True

  MAX-RAM-DESTAGE-SIZE:
    type: int
    default: 1048576
    optional: True

  MAX-RAM-DESTAGE-OPS:
    type: int
    default: 100
    optional: True

  MAX-RAM-DESTAGE-TIME:
    type: int
    optional: True
