FIOL_ACCELERATOR:
  SLURM_CONF:
    ask_user: true
    description: Path to the Slurm configuration of the cluster
    env_var: true
    type: str
    value: /slurm/slurm.conf
  SRO_CLUSTER_THRESHOLD:
    description: null
    env_var: true
    type: int
    value: 2
  SRO_DSC_BINSIZE:
    description: null
    env_var: true
    type: int
    value: 1048576
  SRO_PREFETCH_SIZE:
    description: null
    env_var: true
    type: int
    value: 20971520
  SRO_SEQUENCE_LENGTH:
    description: null
    env_var: true
    type: int
    value: 100
